// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="prng_top_prng_top,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=19.028000,HLS_SYN_LAT=1,HLS_SYN_TPT=2,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=767,HLS_SYN_LUT=1638,HLS_VERSION=2024_1}" *)

module prng_top (
        ap_clk,
        ap_rst_n,
        prng_out,
        prng_out_valid,
        s_axi_CONTROL_AWVALID,
        s_axi_CONTROL_AWREADY,
        s_axi_CONTROL_AWADDR,
        s_axi_CONTROL_WVALID,
        s_axi_CONTROL_WREADY,
        s_axi_CONTROL_WDATA,
        s_axi_CONTROL_WSTRB,
        s_axi_CONTROL_ARVALID,
        s_axi_CONTROL_ARREADY,
        s_axi_CONTROL_ARADDR,
        s_axi_CONTROL_RVALID,
        s_axi_CONTROL_RREADY,
        s_axi_CONTROL_RDATA,
        s_axi_CONTROL_RRESP,
        s_axi_CONTROL_BVALID,
        s_axi_CONTROL_BREADY,
        s_axi_CONTROL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [63:0] prng_out;
output  [0:0] prng_out_valid;
input   s_axi_CONTROL_AWVALID;
output   s_axi_CONTROL_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_CONTROL_AWADDR;
input   s_axi_CONTROL_WVALID;
output   s_axi_CONTROL_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_CONTROL_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_CONTROL_WSTRB;
input   s_axi_CONTROL_ARVALID;
output   s_axi_CONTROL_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_CONTROL_ARADDR;
output   s_axi_CONTROL_RVALID;
input   s_axi_CONTROL_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_CONTROL_RDATA;
output  [1:0] s_axi_CONTROL_RRESP;
output   s_axi_CONTROL_BVALID;
input   s_axi_CONTROL_BREADY;
output  [1:0] s_axi_CONTROL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [0:0] ctrl;
wire   [15:0] init_x1;
wire   [15:0] init_x2;
wire   [15:0] init_x3;
wire   [15:0] init_x4;
reg   [0:0] init_done;
reg   [15:0] x1_reg;
reg   [15:0] x2_reg;
reg   [15:0] x3_reg;
reg   [15:0] s0_reg;
reg   [15:0] s1_reg;
reg   [15:0] s2_reg;
reg   [3:0] rot_cnt;
reg   [29:0] temp_reg;
reg   [63:0] u_prev1;
reg   [63:0] u_prev2;
reg   [0:0] pp_init;
wire   [29:0] grp_fu_351_p2;
reg   [15:0] mul_ln31_reg_362;
wire   [0:0] ctrl_read_read_fu_180_p2;
reg   [0:0] ctrl_read_reg_959;
wire   [15:0] select_ln66_fu_446_p3;
wire   [15:0] select_ln66_3_fu_472_p3;
wire   [15:0] shl_ln19_1_fu_492_p2;
reg   [15:0] shl_ln19_1_reg_1011;
wire   [15:0] sub_ln19_fu_504_p2;
reg   [15:0] sub_ln19_reg_1016;
wire   [15:0] sub_ln43_fu_528_p2;
reg   [15:0] sub_ln43_reg_1021;
wire   [3:0] k_fu_534_p2;
reg   [3:0] k_reg_1026;
wire   [6:0] sub_ln127_fu_544_p2;
reg   [6:0] sub_ln127_reg_1032;
reg   [15:0] ap_phi_mux_x_2_phi_fu_203_p4;
reg   [15:0] x_2_reg_200;
wire   [0:0] init_done_load_load_fu_370_p1;
wire   [15:0] select_ln66_1_fu_454_p3;
reg   [15:0] ap_phi_mux_x_4_phi_fu_213_p4;
reg   [15:0] x_4_reg_210;
wire   [15:0] select_ln66_2_fu_463_p3;
reg  signed [15:0] ap_phi_mux_x_1_phi_fu_223_p4;
reg   [3:0] ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4;
reg   [15:0] x_reg_240;
reg   [15:0] x_5_reg_249;
reg   [15:0] x_3_reg_258;
reg   [29:0] temp_reg_loc_0_reg_269;
reg   [63:0] u_prev1_loc_0_reg_280;
reg   [63:0] u_prev2_loc_0_reg_291;
reg   [0:0] pp_init_flag_0_reg_302;
reg   [0:0] pp_init_loc_0_reg_315;
wire   [63:0] y_t_fu_932_p3;
reg   [63:0] ap_phi_mux_storemerge3_phi_fu_330_p4;
reg   [63:0] storemerge3_reg_326;
wire    ap_CS_fsm_state2;
reg   [0:0] ap_phi_mux_storemerge2_phi_fu_342_p4;
reg   [0:0] storemerge2_reg_338;
wire   [15:0] x1n_fu_618_p2;
wire   [15:0] x2n_fu_665_p2;
wire   [15:0] x3n_fu_712_p2;
wire   [15:0] x4n_fu_751_p2;
wire   [3:0] select_ln133_fu_556_p3;
wire   [63:0] u_t_fu_856_p3;
wire   [0:0] not_pp_init_loc_0_fu_920_p2;
wire   [0:0] pp_init_flag_1_fu_926_p2;
reg  signed [16:0] grp_fu_351_p0;
wire   [29:0] zext_ln118_fu_763_p1;
reg   [15:0] grp_fu_351_p1;
wire   [29:0] zext_ln118_1_fu_768_p1;
wire   [15:0] or_ln66_1_fu_428_p2;
wire   [15:0] or_ln66_fu_422_p2;
wire   [15:0] or_ln66_2_fu_434_p2;
wire   [0:0] icmp_ln66_fu_440_p2;
wire   [15:0] shl_ln19_fu_486_p2;
wire   [15:0] add_ln19_fu_498_p2;
wire   [15:0] shl_ln25_1_fu_516_p2;
wire   [15:0] shl_ln25_fu_510_p2;
wire   [15:0] add_ln43_fu_522_p2;
wire   [6:0] zext_ln127_1_fu_540_p1;
wire   [0:0] icmp_ln133_fu_550_p2;
wire   [15:0] shl_ln13_1_fu_576_p2;
wire   [15:0] shl_ln13_fu_570_p2;
wire   [15:0] add_ln13_fu_594_p2;
wire   [15:0] sub_ln13_fu_600_p2;
wire   [15:0] shl_ln13_2_fu_582_p2;
wire   [15:0] sub_ln13_1_fu_606_p2;
wire   [15:0] shl_ln13_3_fu_588_p2;
wire   [15:0] sub_ln13_2_fu_612_p2;
wire   [15:0] shl_ln19_2_fu_624_p2;
wire   [15:0] sub_ln19_1_fu_636_p2;
wire   [15:0] shl_ln19_3_fu_630_p2;
wire   [15:0] shl_ln37_fu_647_p2;
wire   [15:0] shl_ln37_1_fu_653_p2;
wire   [15:0] sub_ln19_2_fu_641_p2;
wire   [15:0] sub_ln37_fu_659_p2;
wire   [15:0] shl_ln25_2_fu_671_p2;
wire   [15:0] sub_ln25_fu_695_p2;
wire   [15:0] shl_ln43_1_fu_683_p2;
wire   [15:0] sub_ln25_1_fu_700_p2;
wire   [15:0] shl_ln43_fu_677_p2;
wire   [15:0] add_ln25_fu_706_p2;
wire   [15:0] shl_ln43_2_fu_689_p2;
wire   [15:0] shl_ln49_fu_724_p2;
wire   [15:0] add_ln49_fu_730_p2;
wire   [15:0] sub_ln49_fu_736_p2;
wire   [15:0] trunc_ln_fu_741_p4;
wire   [15:0] z_fu_718_p2;
wire   [15:0] inv_z_fu_757_p2;
wire   [63:0] Z_fu_773_p5;
wire   [63:0] zext_ln127_fu_832_p1;
wire   [63:0] zext_ln127_2_fu_841_p1;
wire   [63:0] lshr_ln127_fu_844_p2;
wire   [63:0] shl_ln127_fu_835_p2;
wire   [0:0] icmp_ln126_fu_785_p2;
wire   [63:0] Z_rot_fu_850_p2;
wire   [46:0] trunc_ln153_fu_864_p1;
wire   [16:0] lshr_ln_fu_868_p4;
wire   [20:0] trunc_ln154_fu_886_p1;
wire   [42:0] lshr_ln1_fu_890_p4;
wire   [63:0] rot2_fu_900_p3;
wire   [63:0] xor_ln155_fu_908_p2;
wire   [63:0] rot1_fu_878_p3;
wire   [63:0] xor_ln155_1_fu_914_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_condition_186;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 init_done = 1'd0;
#0 x1_reg = 16'd0;
#0 x2_reg = 16'd0;
#0 x3_reg = 16'd0;
#0 s0_reg = 16'd0;
#0 s1_reg = 16'd0;
#0 s2_reg = 16'd0;
#0 rot_cnt = 4'd0;
#0 temp_reg = 30'd0;
#0 u_prev1 = 64'd0;
#0 u_prev2 = 64'd0;
#0 pp_init = 1'd0;
end

prng_top_CONTROL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
CONTROL_s_axi_U(
    .AWVALID(s_axi_CONTROL_AWVALID),
    .AWREADY(s_axi_CONTROL_AWREADY),
    .AWADDR(s_axi_CONTROL_AWADDR),
    .WVALID(s_axi_CONTROL_WVALID),
    .WREADY(s_axi_CONTROL_WREADY),
    .WDATA(s_axi_CONTROL_WDATA),
    .WSTRB(s_axi_CONTROL_WSTRB),
    .ARVALID(s_axi_CONTROL_ARVALID),
    .ARREADY(s_axi_CONTROL_ARREADY),
    .ARADDR(s_axi_CONTROL_ARADDR),
    .RVALID(s_axi_CONTROL_RVALID),
    .RREADY(s_axi_CONTROL_RREADY),
    .RDATA(s_axi_CONTROL_RDATA),
    .RRESP(s_axi_CONTROL_RRESP),
    .BVALID(s_axi_CONTROL_BVALID),
    .BREADY(s_axi_CONTROL_BREADY),
    .BRESP(s_axi_CONTROL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ctrl(ctrl),
    .init_x1(init_x1),
    .init_x2(init_x2),
    .init_x3(init_x3),
    .init_x4(init_x4),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

prng_top_mul_17s_16ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_17s_16ns_30_1_1_U1(
    .din0(grp_fu_351_p0),
    .din1(grp_fu_351_p1),
    .dout(grp_fu_351_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            pp_init_flag_0_reg_302 <= 1'd1;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            pp_init_flag_0_reg_302 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            pp_init_loc_0_reg_315 <= 1'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            pp_init_loc_0_reg_315 <= pp_init;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (ctrl_read_read_fu_180_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge2_reg_338 <= 1'd0;
    end else if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        storemerge2_reg_338 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (ctrl_read_read_fu_180_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge3_reg_326 <= 64'd0;
    end else if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        storemerge3_reg_326 <= y_t_fu_932_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            temp_reg_loc_0_reg_269 <= 30'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            temp_reg_loc_0_reg_269 <= temp_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            u_prev1_loc_0_reg_280 <= 64'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            u_prev1_loc_0_reg_280 <= u_prev1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            u_prev2_loc_0_reg_291 <= 64'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            u_prev2_loc_0_reg_291 <= u_prev2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            x_2_reg_200 <= select_ln66_1_fu_454_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            x_2_reg_200 <= x2_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            x_3_reg_258 <= 16'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            x_3_reg_258 <= s1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            x_4_reg_210 <= select_ln66_2_fu_463_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            x_4_reg_210 <= x3_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            x_5_reg_249 <= select_ln66_3_fu_472_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            x_5_reg_249 <= s0_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            x_reg_240 <= select_ln66_fu_446_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            x_reg_240 <= x1_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ctrl_read_reg_959 <= ctrl;
        k_reg_1026 <= k_fu_534_p2;
        mul_ln31_reg_362 <= grp_fu_351_p2;
        shl_ln19_1_reg_1011[15 : 7] <= shl_ln19_1_fu_492_p2[15 : 7];
        sub_ln127_reg_1032 <= sub_ln127_fu_544_p2;
        sub_ln19_reg_1016 <= sub_ln19_fu_504_p2;
        sub_ln43_reg_1021 <= sub_ln43_fu_528_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (init_done_load_load_fu_370_p1 == 1'd0))) begin
        init_done <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (pp_init_flag_1_fu_926_p2 == 1'd1))) begin
        pp_init <= not_pp_init_loc_0_fu_920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        rot_cnt <= select_ln133_fu_556_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        s0_reg <= x4n_fu_751_p2;
        s1_reg <= x_5_reg_249;
        s2_reg <= x_3_reg_258;
        temp_reg <= grp_fu_351_p2;
        u_prev1 <= u_t_fu_856_p3;
        u_prev2 <= u_prev1_loc_0_reg_280;
        x1_reg <= x1n_fu_618_p2;
        x2_reg <= x2n_fu_665_p2;
        x3_reg <= x3n_fu_712_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 = 4'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 = rot_cnt;
        end else begin
            ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 = 'bx;
    end
end

always @ (*) begin
    if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_storemerge2_phi_fu_342_p4 = 1'd1;
    end else begin
        ap_phi_mux_storemerge2_phi_fu_342_p4 = storemerge2_reg_338;
    end
end

always @ (*) begin
    if (((ctrl_read_reg_959 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_storemerge3_phi_fu_330_p4 = y_t_fu_932_p3;
    end else begin
        ap_phi_mux_storemerge3_phi_fu_330_p4 = storemerge3_reg_326;
    end
end

always @ (*) begin
    if (((ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            ap_phi_mux_x_1_phi_fu_223_p4 = 16'd0;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            ap_phi_mux_x_1_phi_fu_223_p4 = s2_reg;
        end else begin
            ap_phi_mux_x_1_phi_fu_223_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_x_1_phi_fu_223_p4 = 'bx;
    end
end

always @ (*) begin
    if (((ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            ap_phi_mux_x_2_phi_fu_203_p4 = select_ln66_1_fu_454_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            ap_phi_mux_x_2_phi_fu_203_p4 = x2_reg;
        end else begin
            ap_phi_mux_x_2_phi_fu_203_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_x_2_phi_fu_203_p4 = 'bx;
    end
end

always @ (*) begin
    if (((ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((init_done_load_load_fu_370_p1 == 1'd0)) begin
            ap_phi_mux_x_4_phi_fu_213_p4 = select_ln66_2_fu_463_p3;
        end else if ((init_done_load_load_fu_370_p1 == 1'd1)) begin
            ap_phi_mux_x_4_phi_fu_213_p4 = x3_reg;
        end else begin
            ap_phi_mux_x_4_phi_fu_213_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_x_4_phi_fu_213_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_351_p0 = zext_ln118_fu_763_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_351_p0 = ap_phi_mux_x_1_phi_fu_223_p4;
    end else begin
        grp_fu_351_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_351_p1 = zext_ln118_1_fu_768_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_351_p1 = 16'd50;
    end else begin
        grp_fu_351_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Z_fu_773_p5 = {{{{x4n_fu_751_p2}, {x3n_fu_712_p2}}, {x2n_fu_665_p2}}, {x1n_fu_618_p2}};

assign Z_rot_fu_850_p2 = (shl_ln127_fu_835_p2 | lshr_ln127_fu_844_p2);

assign add_ln13_fu_594_p2 = (shl_ln13_1_fu_576_p2 + x_reg_240);

assign add_ln19_fu_498_p2 = (shl_ln19_1_fu_492_p2 + ap_phi_mux_x_2_phi_fu_203_p4);

assign add_ln25_fu_706_p2 = (sub_ln25_1_fu_700_p2 + shl_ln43_fu_677_p2);

assign add_ln43_fu_522_p2 = (shl_ln25_1_fu_516_p2 + ap_phi_mux_x_4_phi_fu_213_p4);

assign add_ln49_fu_730_p2 = (shl_ln49_fu_724_p2 + x_2_reg_200);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_condition_186 = ((ap_start == 1'b1) & (ctrl_read_read_fu_180_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ctrl_read_read_fu_180_p2 = ctrl;

assign icmp_ln126_fu_785_p2 = ((k_reg_1026 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_550_p2 = ((ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_440_p2 = ((or_ln66_2_fu_434_p2 == 16'd0) ? 1'b1 : 1'b0);

assign init_done_load_load_fu_370_p1 = init_done;

assign inv_z_fu_757_p2 = (z_fu_718_p2 ^ 16'd65535);

assign k_fu_534_p2 = (ap_phi_mux_rot_cnt_loc_0_phi_fu_233_p4 + 4'd1);

assign lshr_ln127_fu_844_p2 = Z_fu_773_p5 >> zext_ln127_2_fu_841_p1;

assign lshr_ln1_fu_890_p4 = {{u_prev2_loc_0_reg_291[63:21]}};

assign lshr_ln_fu_868_p4 = {{u_prev1_loc_0_reg_280[63:47]}};

assign not_pp_init_loc_0_fu_920_p2 = (pp_init_loc_0_reg_315 ^ 1'd1);

assign or_ln66_1_fu_428_p2 = (init_x4 | init_x3);

assign or_ln66_2_fu_434_p2 = (or_ln66_fu_422_p2 | or_ln66_1_fu_428_p2);

assign or_ln66_fu_422_p2 = (init_x2 | init_x1);

assign pp_init_flag_1_fu_926_p2 = (pp_init_flag_0_reg_302 | not_pp_init_loc_0_fu_920_p2);

assign prng_out = ap_phi_mux_storemerge3_phi_fu_330_p4;

assign prng_out_valid = ap_phi_mux_storemerge2_phi_fu_342_p4;

assign rot1_fu_878_p3 = {{trunc_ln153_fu_864_p1}, {lshr_ln_fu_868_p4}};

assign rot2_fu_900_p3 = {{trunc_ln154_fu_886_p1}, {lshr_ln1_fu_890_p4}};

assign select_ln133_fu_556_p3 = ((icmp_ln133_fu_550_p2[0:0] == 1'b1) ? 4'd0 : k_fu_534_p2);

assign select_ln66_1_fu_454_p3 = ((icmp_ln66_fu_440_p2[0:0] == 1'b1) ? 16'd2000 : init_x2);

assign select_ln66_2_fu_463_p3 = ((icmp_ln66_fu_440_p2[0:0] == 1'b1) ? 16'd3000 : init_x3);

assign select_ln66_3_fu_472_p3 = ((icmp_ln66_fu_440_p2[0:0] == 1'b1) ? 16'd4000 : init_x4);

assign select_ln66_fu_446_p3 = ((icmp_ln66_fu_440_p2[0:0] == 1'b1) ? 16'd1000 : init_x1);

assign shl_ln127_fu_835_p2 = Z_fu_773_p5 << zext_ln127_fu_832_p1;

assign shl_ln13_1_fu_576_p2 = x_reg_240 << 16'd7;

assign shl_ln13_2_fu_582_p2 = x_reg_240 << 16'd3;

assign shl_ln13_3_fu_588_p2 = x_reg_240 << 16'd2;

assign shl_ln13_fu_570_p2 = x_reg_240 << 16'd9;

assign shl_ln19_1_fu_492_p2 = ap_phi_mux_x_2_phi_fu_203_p4 << 16'd7;

assign shl_ln19_2_fu_624_p2 = x_2_reg_200 << 16'd3;

assign shl_ln19_3_fu_630_p2 = x_2_reg_200 << 16'd1;

assign shl_ln19_fu_486_p2 = ap_phi_mux_x_2_phi_fu_203_p4 << 16'd9;

assign shl_ln25_1_fu_516_p2 = ap_phi_mux_x_4_phi_fu_213_p4 << 16'd7;

assign shl_ln25_2_fu_671_p2 = x_4_reg_210 << 16'd3;

assign shl_ln25_fu_510_p2 = ap_phi_mux_x_4_phi_fu_213_p4 << 16'd9;

assign shl_ln37_1_fu_653_p2 = x_3_reg_258 << 16'd4;

assign shl_ln37_fu_647_p2 = x_3_reg_258 << 16'd6;

assign shl_ln43_1_fu_683_p2 = x_5_reg_249 << 16'd4;

assign shl_ln43_2_fu_689_p2 = x_5_reg_249 << 16'd1;

assign shl_ln43_fu_677_p2 = x_5_reg_249 << 16'd6;

assign shl_ln49_fu_724_p2 = x_2_reg_200 << 16'd4;

assign sub_ln127_fu_544_p2 = ($signed(7'd64) - $signed(zext_ln127_1_fu_540_p1));

assign sub_ln13_1_fu_606_p2 = (sub_ln13_fu_600_p2 - shl_ln13_2_fu_582_p2);

assign sub_ln13_2_fu_612_p2 = (sub_ln13_1_fu_606_p2 - shl_ln13_3_fu_588_p2);

assign sub_ln13_fu_600_p2 = (shl_ln13_fu_570_p2 - add_ln13_fu_594_p2);

assign sub_ln19_1_fu_636_p2 = (sub_ln19_reg_1016 - shl_ln19_2_fu_624_p2);

assign sub_ln19_2_fu_641_p2 = (sub_ln19_1_fu_636_p2 - shl_ln19_3_fu_630_p2);

assign sub_ln19_fu_504_p2 = (shl_ln19_fu_486_p2 - add_ln19_fu_498_p2);

assign sub_ln25_1_fu_700_p2 = (sub_ln25_fu_695_p2 - shl_ln43_1_fu_683_p2);

assign sub_ln25_fu_695_p2 = (sub_ln43_reg_1021 - shl_ln25_2_fu_671_p2);

assign sub_ln37_fu_659_p2 = (shl_ln37_fu_647_p2 - shl_ln37_1_fu_653_p2);

assign sub_ln43_fu_528_p2 = (shl_ln25_fu_510_p2 - add_ln43_fu_522_p2);

assign sub_ln49_fu_736_p2 = (shl_ln19_1_reg_1011 - add_ln49_fu_730_p2);

assign trunc_ln153_fu_864_p1 = u_prev1_loc_0_reg_280[46:0];

assign trunc_ln154_fu_886_p1 = u_prev2_loc_0_reg_291[20:0];

assign trunc_ln_fu_741_p4 = {{temp_reg_loc_0_reg_269[29:14]}};

assign u_t_fu_856_p3 = ((icmp_ln126_fu_785_p2[0:0] == 1'b1) ? Z_fu_773_p5 : Z_rot_fu_850_p2);

assign x1n_fu_618_p2 = (sub_ln13_2_fu_612_p2 + mul_ln31_reg_362);

assign x2n_fu_665_p2 = (sub_ln19_2_fu_641_p2 + sub_ln37_fu_659_p2);

assign x3n_fu_712_p2 = (add_ln25_fu_706_p2 - shl_ln43_2_fu_689_p2);

assign x4n_fu_751_p2 = (sub_ln49_fu_736_p2 + trunc_ln_fu_741_p4);

assign xor_ln155_1_fu_914_p2 = (xor_ln155_fu_908_p2 ^ rot1_fu_878_p3);

assign xor_ln155_fu_908_p2 = (u_t_fu_856_p3 ^ rot2_fu_900_p3);

assign y_t_fu_932_p3 = ((pp_init_loc_0_reg_315[0:0] == 1'b1) ? xor_ln155_1_fu_914_p2 : u_t_fu_856_p3);

assign z_fu_718_p2 = (x_5_reg_249 + x_4_reg_210);

assign zext_ln118_1_fu_768_p1 = inv_z_fu_757_p2;

assign zext_ln118_fu_763_p1 = z_fu_718_p2;

assign zext_ln127_1_fu_540_p1 = k_fu_534_p2;

assign zext_ln127_2_fu_841_p1 = sub_ln127_reg_1032;

assign zext_ln127_fu_832_p1 = k_reg_1026;

always @ (posedge ap_clk) begin
    shl_ln19_1_reg_1011[6:0] <= 7'b0000000;
end

endmodule //prng_top
