// Auto-generated by hw/generate_params.py — DO NOT EDIT manually.
// R1-LY synthesis: n=4, A_odd=371, B_even=50, word_size=16
// Generated: 2026-05-13 16:28:33

#ifndef CHAOS_PARAMS_H
#define CHAOS_PARAMS_H

// ---- Expansion coefficients (odd) ----
#define A_J1_0  371
#define A_J1_1  373
#define A_J1_2  375

// ---- Coupling coefficients (even) ----
#define A_JN_0  50
#define A_JN_1  48
#define A_JN_2  46

// ---- Feedback ----
#define B_VAL  111

// ---- Derived constants ----
#define A_MIN  371
#define C_VAL  111.144  // Lipschitz bound (float, for reference only)

#endif // CHAOS_PARAMS_H
