// Auto-generated by hw/generate_params.py — DO NOT EDIT.
// Shift-and-add constant multipliers (zero DSP blocks).
// Generated: 2026-05-13 16:28:33

#ifndef SHIFT_MUL_H
#define SHIFT_MUL_H

#include <ap_int.h>

// 371 = 256+64+32+16+2+1  (5 add/sub ops)
static inline ap_uint<16> mul_A_J1_0(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<9)-(x<<7)-(x<<3)-(x<<2)-x;
}

// 373 = 256+64+32+16+4+1  (5 add/sub ops)
static inline ap_uint<16> mul_A_J1_1(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<9)-(x<<7)-(x<<3)-(x<<1)-x;
}

// 375 = 256+64+32+16+4+2+1  (4 add/sub ops)
static inline ap_uint<16> mul_A_J1_2(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<9)-(x<<7)-(x<<3)-x;
}

// 50 = 32+16+2  (3 add/sub ops)
static inline ap_uint<16> mul_A_JN_0(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<5)+(x<<4)+(x<<1);
}

// 48 = 32+16  (2 add/sub ops)
static inline ap_uint<16> mul_A_JN_1(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<5)+(x<<4);
}

// 46 = 32+8+4+2  (4 add/sub ops)
static inline ap_uint<16> mul_A_JN_2(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<6)-(x<<4)-(x<<1);
}

// 111 = 64+32+8+4+2+1
static inline ap_uint<16> mul_B_VAL(ap_uint<16> x) {
#pragma HLS INLINE
    return (x<<7)-(x<<4)-x;
}

#endif // SHIFT_MUL_H
